// Handles additional code and business logic for auth matters.

const dbClient = require('../utils/db').dbClient;
const emailValidator = require('deep-email-validator');

/**
 * Check if the passed argument is a valid name.
 * The name is checked to be a string and not empty.
 * @param {String} name the name to validate
 */
function isValidName(name, isUsername=false) {
    if (name) {
        if (name.length > 0) {
            return true;
        }
    }
    
    return false;
}

/**
 * Validates an email address using deep-email-validator.
 * Validates that:
 *      - email looks like one, eg. with '@' and '.' to the right.
 *      - common email typos using `mailcheck`.
 *      - email was not generated by a disposable email service, using
 *        `disposable-email-domains` module.
 *      - mx records are present on DNS.
 *      - SMTP server is running.
 *      - mailbox exists on SMTP server.
 * @requires deep-email-validator module.
 * @param {String} email the email to validate
 * Returns true if valid, otherwise false
 */
async function isValidEmail(email) {
    try {
        return await emailValidator.validate(email);
    } catch (error) {
        console.log(`Error while validating email: ${error}`);
    }
}

/**
 * Performs password validation according to the following specifications:
 * Contains at least:
 * - One uppercase letter
 * - One lowercase letter
 * - One special character
 * - One digit
 * - A total length of 8 characters
 * @param {String} password the password to validate
 * Returns true if validate, otherwise false.
 */
function isValidPassword(password) {
    if (typeof password !== 'string') {
        return false;
    }
    if (password.length < 8) {
        return false;
    }

    let hasUpperCase = false;
    let hasLowerCase = false;
    let hasSpecialChar = false;
    let hasNumber = false;

    for (const char of password) {
        if (hasUpperCase && hasLowerCase && hasSpecialChar && hasNumber) {
            return true;
        } else if (char >= 'A' && char <= 'Z') {
            hasUpperCase = true;
        } else if (char >= 'a' && char <= 'z') {
            hasLowerCase = true;
        } else if ('!@#$%^&*()_-+=?/<>{}[]|'.includes(char)) {
            hasSpecialChar = true;
        } else if (/^\d$/.test(char)) {
            hasNumber = true;
        }
    }

    return (hasUpperCase && hasLowerCase && hasSpecialChar && hasNumber);
}

/**
* Searches for an existing user with the given identifier.
* A query to find a user, is constructed by dynamically setting the field
* and value of the field.
* @param {String} identifier the identifier to find a user with, eg. id, email, username
* @param {String} field a field used to uniquely find a user with. 
* @returns the user if found, otherwise null.
*/
async function findUser(identifier, field) {
    return await dbClient.findUser(identifier, field);
}

/**
 * Inserts one user into the database.
 * @param {Object} userInfo the information of the new user.
 */
async function insertUser(userInfo) {
    const result = await dbClient.insertUser(userInfo);
    return result;
}

module.exports = {
    isValidEmail,
    isValidPassword,
    findUser,
    insertUser
}

